---
version: '3'

services:
  postgres:
    container_name: 'postgres-my-app'
    image: 'postgis/postgis:14-3.3-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'changeme'
      POSTGRES_DB: 'my-app'
      PGDATA: '/data/my-app'
    ports:
      - '5432:5432'
    restart: 'always'

  server:
    platform: linux/x86_64
    container_name: 'my-app'
    image: my-app
    entrypoint: ''
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    expose:
      - 4000
    environment:
      - POSTGRES_URL=postgres://postgres:changeme@postgres:5432/my-app?sslmode=disable
      - NODE_ENV=development
    command: npm run start:dev
    volumes:
      - /app/node_modules
      - .:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: 'always'
